import { IPageForIndex } from '../viewModels';

export const RoutePagesInfo: IPageForIndex[] = [
    {
      title: '启动ability获取结果',
      url: 'pages/StartAbilityForResult'
    },
    {
      title: 'Navigation组件导航路由实践',
      url: 'pages/NavigationPage'
    },
    {
      title: '相册选择/下拉刷新/上滑加载',
      url: 'pages/NewsCreateLoadRefresh'
    },
    {
      title: '自定义二次确认弹窗',
      url: 'pages/CustomDialogPage'
    },
    {
      title: 'ActionSheet列表选择对话框',
      url: 'pages/ActionSheetOrListSelectDialog'
    },
    {
      title: 'openLink启动其他模块的Ability进入指定页面',
      url: 'pages/StartAbilitySpecifiedPage'
    },
    {
      title: '文本选择器/文本选择对话框',
      url: 'pages/TextPickerPage'
    },
    {
      title: 'Refresh刷新容器/onMove实现拖放',
      url: 'pages/RefreshContainerComponentExample'
    },
    {
      title: '使用HSP动态共享包中的资源',
      url: 'pages/UseHspContent'
    },
    {
      title: 'LocalStorage装饰器不能在V2组件中使用, 其他方式实现一样效果[1]',
      url: 'pages/LocalStorageUsage'
    },
    {
      title: '配合LocalStorageUsage页面使用LocalStorage[2]',
      url: 'pages/LocalStorageUsageTest'
    },
    {
      title: 'PersistentStorage和Environment使用',
      url: 'pages/PersistentStorage_Environment_Usage'
    },
    {
      title: '事件发射器Emitter使用示例',
      url: 'pages/EmitterUsage'
    },
    {
      title: 'ProgressMask遮罩中间镂空显示逐渐',
      url: 'pages/ProgressMaskAttributeUsage'
    },
    {
      title: 'counter计数器容器和隐私遮罩属性obscured',
      url: 'pages/ObscuredAttributeAndCounter'
    },
    {
      title: '使用组件属性bindSheet实现半屏模态框',
      url: 'pages/BindSheetAttribute'
    },
    {
      title: '使用组件属性bindContentCover实现全屏模态框',
      url: 'pages/BindContentCoverUsage'
    },
    {
      title: 'TextOverflow.MARQUEE属性代替Marquee组件',
      url: 'pages/TextOverflowMARQUEE'
    },
    {
      title: 'Video组件播放音频和视频',
      url: 'pages/VideoPlayAudio'
    },
    {
      title: 'notificationManager文本通知示例',
      url: 'pages/NotificationManagerTextUsage'
    },
    {
      title: 'notificationManager进度通知示例',
      url: 'pages/NotificationManagerProgressBar'
    },
    {
      title: 'notificationManager意图代理通知示例【待解决获取意图代理对象为{}】',
      url: 'pages/NotificationManagerWantAgent'
    },
    {
      title: 'ReminderAgentManager倒计时提醒通知',
      url: 'pages/ReminderAgentManagerTimer'
    },
    {
      title: 'ReminderAgentManager闹钟提醒通知',
      url: 'pages/ReminderAgentManagerAlarm'
    },
    {
      title: 'ReminderAgentManager日历提醒通知',
      url: 'pages/ReminderAgentManagerCalendar'
    },
    {
      title: '三方库Lottie使用示例',
      url: 'pages/ThirdPartLibUsageLottie'
    }
  ];