import { IPageForIndex } from '../viewModels';

export const RoutePagesInfo: IPageForIndex[] = [
    {
      title: '启动ability获取结果',
      url: 'pages/StartAbilityForResult'
    },
    {
      title: 'Navigation组件导航路由实践',
      url: 'pages/NavigationPage'
    },
    {
      title: '相册选择/下拉刷新/上滑加载',
      url: 'pages/NewsCreateLoadRefresh'
    },
    {
      title: '自定义二次确认弹窗',
      url: 'pages/CustomDialogPage'
    },
    {
      title: 'ActionSheet列表选择对话框',
      url: 'pages/ActionSheetOrListSelectDialog'
    },
    {
      title: 'openLink启动其他模块的Ability进入指定页面',
      url: 'pages/StartAbilitySpecifiedPage'
    },
    {
      title: '文本选择器/文本选择对话框',
      url: 'pages/TextPickerPage'
    },
    {
      title: 'Refresh刷新容器/onMove实现拖放',
      url: 'pages/RefreshContainerComponentExample'
    },
    {
      title: '使用HSP动态共享包中的资源',
      url: 'pages/UseHspContent'
    },
    {
      title: 'LocalStorage装饰器不能在V2组件中使用, 其他方式实现一样效果[1]',
      url: 'pages/LocalStorageUsage'
    },
    {
      title: '配合LocalStorageUsage页面使用LocalStorage[2]',
      url: 'pages/LocalStorageUsageTest'
    },
    {
      title: 'PersistentStorage和Environment使用',
      url: 'pages/PersistentStorage_Environment_Usage'
    },
    {
      title: '事件发射器Emitter使用示例',
      url: 'pages/EmitterUsage'
    }
  ];